2023/10/28 12:34:46 failed to dial tcp connection, retrying
2023/10/28 12:34:47 failed to dial tcp connection, retrying
[2023-10-28T12:34:47.739Z] info  code-server 4.11.0 85e083580dec27ef19827ff42d3c9257d56ea7e3
[2023-10-28T12:34:47.741Z] info  Using user-data-dir ~/.local/share/code-server
[2023-10-28T12:34:47.753Z] info  Using config file ~/.config/code-server/config.yaml
[2023-10-28T12:34:47.753Z] info  HTTP server listening on http://127.0.0.1:8080/
[2023-10-28T12:34:47.753Z] info    - Authentication is disabled
[2023-10-28T12:34:47.754Z] info    - Not serving HTTPS
====================================>token: 3fb19bf5-9eda-4de8-a7e5-4e420500797e
[12:35:50] 




[12:35:50] Extension host agent started.
[12:35:53] [127.0.0.1][4d5916bf][ManagementConnection] New connection established.
[12:35:53] [127.0.0.1][91c5b2b2][ExtensionHostConnection] New connection established.
[12:35:53] [127.0.0.1][91c5b2b2][ExtensionHostConnection] <379> Launched Extension Host Process.
[12:35:57] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
[2023-10-28T12:38:03.190Z] error Failed to get latest version [38;2;140;140;140m{"error":"connect ETIMEDOUT 20.205.243.168:443"}[0m
[12:38:17] [File Watcher (parcel)] Inotify limit reached (ENOSPC) (path: /opt/conda/lib/python3.8)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8986f1]

goroutine 433 [running]:
http_reverse_proxy/client.sendHttpRequestAndReplyHttpResponse(0xc0005167d0?, 0x7b30ae?, 0xc00039a0a0, 0xc000296060)
	/builds/hitminer/http_reverse_proxy/client/http_client.go:51 +0xb1
created by http_reverse_proxy/client.startHttpClient
	/builds/hitminer/http_reverse_proxy/client/http_client.go:34 +0x1ea
